/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Match, Competitor } from './types';

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'm1',
    matchNumber: 1,
    homeTeam: 'MEXICO',
    awayTeam: 'ECUADOR',
    homeCode: 'MEX',
    awayCode: 'ECU',
    homeFlag: 'https://flagcdn.com/w160/mx.png',
    awayFlag: 'https://flagcdn.com/w160/ec.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 11, 15:00 at Estadio Azteca, Mexico City',
    pointsPotential: 3,
  },
  {
    id: 'm2',
    matchNumber: 2,
    homeTeam: 'SWEDEN',
    awayTeam: 'ALGERIA',
    homeCode: 'SWE',
    awayCode: 'ALG',
    homeFlag: 'https://flagcdn.com/w160/se.png',
    awayFlag: 'https://flagcdn.com/w160/dz.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 11, 18:00 at Estadio Guadalajara, Guadalajara',
    pointsPotential: 3,
  },
  {
    id: 'm3',
    matchNumber: 3,
    homeTeam: 'CANADA',
    awayTeam: 'CROATIA',
    homeCode: 'CAN',
    awayCode: 'CRO',
    homeFlag: 'https://flagcdn.com/w160/ca.png',
    awayFlag: 'https://flagcdn.com/w160/hr.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 12, 14:00 at Toronto Stadium (BMO Field), Toronto',
    pointsPotential: 3,
  },
  {
    id: 'm4',
    matchNumber: 4,
    homeTeam: 'USA',
    awayTeam: 'MOROCCO',
    homeCode: 'USA',
    awayCode: 'MAR',
    homeFlag: 'https://flagcdn.com/w160/us.png',
    awayFlag: 'https://flagcdn.com/w160/ma.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 12, 17:00 at L.A. Stadium (SoFi), Los Angeles',
    pointsPotential: 3,
  },
  {
    id: 'm5',
    matchNumber: 5,
    homeTeam: 'BELGIUM',
    awayTeam: 'SOUTH KOREA',
    homeCode: 'BEL',
    awayCode: 'KOR',
    homeFlag: 'https://flagcdn.com/w160/be.png',
    awayFlag: 'https://flagcdn.com/w160/kr.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 12, 20:00 at BC Place, Vancouver',
    pointsPotential: 3,
  },
  {
    id: 'm6',
    matchNumber: 6,
    homeTeam: 'JAPAN',
    awayTeam: 'SENEGAL',
    homeCode: 'JPN',
    awayCode: 'SEN',
    homeFlag: 'https://flagcdn.com/w160/jp.png',
    awayFlag: 'https://flagcdn.com/w160/sn.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 12, 21:00 at Seattle Stadium, Seattle',
    pointsPotential: 3,
  },
  {
    id: 'm7',
    matchNumber: 7,
    homeTeam: 'ARGENTINA',
    awayTeam: 'POLAND',
    homeCode: 'ARG',
    awayCode: 'POL',
    homeFlag: 'https://flagcdn.com/w160/ar.png',
    awayFlag: 'https://flagcdn.com/w160/pl.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 13, 15:00 at Estadio Monterrey, Monterrey',
    pointsPotential: 3,
  },
  {
    id: 'm8',
    matchNumber: 8,
    homeTeam: 'ENGLAND',
    awayTeam: 'JAPAN',
    homeCode: 'ENG',
    awayCode: 'JPN',
    homeFlag: 'https://flagcdn.com/w160/gb-eng.png',
    awayFlag: 'https://flagcdn.com/w160/jp.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 14, 18:00 at Gillette Stadium, Boston',
    pointsPotential: 3,
  },
  {
    id: 'm9',
    matchNumber: 9,
    homeTeam: 'SPAIN',
    awayTeam: 'BRAZIL',
    homeCode: 'ESP',
    awayCode: 'BRA',
    homeFlag: 'https://flagcdn.com/w160/es.png',
    awayFlag: 'https://flagcdn.com/w160/br.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 15, 21:00 at Stanford Stadium, San Francisco',
    pointsPotential: 3,
  },
  {
    id: 'm10',
    matchNumber: 10,
    homeTeam: 'PORTUGAL',
    awayTeam: 'NETHERLANDS',
    homeCode: 'POR',
    awayCode: 'NED',
    homeFlag: 'https://flagcdn.com/w160/pt.png',
    awayFlag: 'https://flagcdn.com/w160/nl.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 16, 21:00 at MetLife Stadium, New Jersey',
    pointsPotential: 3,
  },
  {
    id: 'm11',
    matchNumber: 11,
    homeTeam: 'FRANCE',
    awayTeam: 'GERMANY',
    homeCode: 'FRA',
    awayCode: 'GER',
    homeFlag: 'https://flagcdn.com/w160/fr.png',
    awayFlag: 'https://flagcdn.com/w160/de.png',
    status: 'upcoming',
    stage: 'group',
    timeLabel: 'Upcoming • June 17, 21:00 at Lincoln Financial Field, Philadelphia',
    pointsPotential: 3,
  },
  // Knockout match 1
  {
    id: 'm_r16_1',
    matchNumber: 49,
    homeTeam: 'ARGENTINA',
    awayTeam: 'FRANCE',
    homeCode: 'ARG',
    awayCode: 'FRA',
    homeFlag: 'https://flagcdn.com/w160/ar.png',
    awayFlag: 'https://flagcdn.com/w160/fr.png',
    status: 'upcoming',
    stage: 'r16',
    timeLabel: 'Round of 16 • June 29, 18:00',
    pointsPotential: 3,
  },
  // Knockout match 2
  {
    id: 'm_qf_1',
    matchNumber: 57,
    homeTeam: 'USA',
    awayTeam: 'BRAZIL',
    homeCode: 'USA',
    awayCode: 'BRA',
    homeFlag: 'https://flagcdn.com/w160/us.png',
    awayFlag: 'https://flagcdn.com/w160/br.png',
    status: 'upcoming',
    stage: 'quarter',
    timeLabel: 'Quarter Finals • July 04, 21:00',
    pointsPotential: 3,
  },
  // Knockout match 3
  {
    id: 'm_sf_1',
    matchNumber: 61,
    homeTeam: 'SPAIN',
    awayTeam: 'ENGLAND',
    homeCode: 'ESP',
    awayCode: 'ENG',
    homeFlag: 'https://flagcdn.com/w160/es.png',
    awayFlag: 'https://flagcdn.com/w160/gb-eng.png',
    status: 'upcoming',
    stage: 'semi',
    timeLabel: 'Semi Finals • July 09, 21:00',
    pointsPotential: 3,
  },
];

export const GLOBAL_LEADERBOARD: Competitor[] = [
  {
    rank: 1,
    name: 'MarcusVieri',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3yB0Y-21QKg0qxj9W1EdegaUl72YNBtSp6U5r9GuCO2kNReH_9Ex73DhmNPUgEN5zk0rVevhq7MOk45U-6mR1gIvIs55vd4Ur34ur3fjslhAF8Ay8Wc1gauTy6RY4U7cey92zmBG7xVoS_bkh6XJR1DNpZ29CgRMs2cbP4SM-GycBVe8LgV12EDU2h4C0GdNy5ZOstMf77YwOFGoC0zg7wQL5pXHlP8k-68nFemZ2Zo-a3vMqSNyXOaygblkqpkvkNjHyH1Fl7a4',
    points: 15,
    exactScores: 3,
    correctOutcomes: 6,
    winRate: '75%',
  },
  {
    rank: 2,
    name: 'Alex Predicted',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDsvpz5dSu_zVlg12Uyf1xTWiSC_7TL15MOQYiinGcsEK1DGncmWDT6swP9kFJXA8NmY1HmHbWH-_CoG2liD9wtxWoK9839e-QvW1IQtHIvqyW1lwUNmg1GOI6L_XjYO3ku0sq4ftDh1xCZGNxg2tNj4rUvJSLfD6ZgvCBOY4dHzQWK202DZVVMBoVqEmZA4U3zzX3vFRq-qHpr8nbgu9W5uBKfw9yu50qMkd42Hj6vOWM9-KI0RqP79n-KdUEB5VIcoiHkhy67-J8',
    points: 11,
    exactScores: 2,
    correctOutcomes: 5,
    winRate: '71%',
  },
  {
    rank: 3,
    name: 'GoalGetter99',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBv9_Aw7JIvmS2pIZ_Uz100LBt7jpwOShoyKdk_p71-ReW8m5EsorSygXnjNOvyXu0hkhJsaHLxCitxuBJAFZNw7hQBThn-7LZJoRTpMst5fc2NwFysrba9ZoZjBon6RCqoBcSsJStkZKmTIygc1RaiSECTZke3jKFJsTxFykwIghcuhBNfOab3ScBPYmdsFTX0d6qCPeycxOJeDeVly1aS4ymjcx-_AzZUC5D9RZzoPgUBzWipABwo5wFAcD55WQrTNkZJroTY1so',
    points: 9,
    exactScores: 1,
    correctOutcomes: 6,
    winRate: '68%',
  },
  {
    rank: 4,
    name: 'SarahStats',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPmIxuer-fAlUnGSCrHY9eI4euU0ulq8g6pm9CbDVY9BA3_vW6QBHKXC5mJVKOH8_5hAtYulCh9VvO_PWsxfWskYunQ0R4NwgZse25vD8-26HVA896ZywQSVxcZvphPMHGR72qSHIMn5HV5mugONIGm0ZLNgJpENrNHBTCcbXu_C7l7wZT2EaFadlsGeHDCfliKWI_taPYFDAEZ7BwkpTNhHrY5bBM8TLhA7eSeWiScyq0jn-07EuUDZ88bCcSfTSPDMf9t3hjcp0',
    points: 7,
    exactScores: 1,
    correctOutcomes: 4,
    winRate: '66%',
  },
];

export const FRIENDS_LEADERBOARD: Competitor[] = [
  {
    rank: 1,
    name: 'PulisicFanatic',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-YPL3-SEZtZ8S8zuDFzmn5B45fQJvL-30-K80A8ctd8CmmheATrUXI_mqe9-OZchj3lFNQhM5WZeq2pvXQgMWSh64hxLKIRTh0UPCa1edjJKXNcrO-EXCLn3TOYGrJ4yA1KunznGb0ODY6dvU8g-w-5BX9GpMLViW0GAu6LwyFbi3LJJ4Fs2Vn_ewp4ISq8YpXzmMZvqdrZdLMB-t1T6KLRcu0xhatmDqul5hgS33lqkkQb6gigz7uIP7yUeD7PI-sCK23vWXeWs',
    points: 10,
    exactScores: 2,
    correctOutcomes: 4,
    winRate: '78%',
  },
  {
    rank: 2,
    name: 'WorldCupKing',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyRiqulSiIjgps7RsasixNdnx85SkNr7aj_5PWB8GXbknu_x5cMukOsYQUMYvpLBmCCVFLP-iPGPszETYR-4KcbirMkuDTNSxXPQaXbjYMzZ0ZS2uRReFoiJzrYnX6eaX71nOkrVUWGUiFxw2Q8x94ExG_pPFiyhDZREeemKoAz7bt81OzV5vlLJzRTRvDMLLiWkpbJcRte2EBlw5rji66mfZQsMXSo2iOhjd491BdTt4DWjMa_1jHv3nyp01MPtNvnxra5ulsYac',
    points: 6,
    exactScores: 1,
    correctOutcomes: 3,
    winRate: '73%',
  },
  {
    rank: 3,
    name: 'DomerPrediction',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAVA1mT9Q7C0l8SygcT1g5miThrH-3mxJXL43gGzUMkDajBecGzIyVBjsT6_eJ8MQU9GOWEQMaBwu6uz3WFiZfrfxx_AhyR_xWWGPwnvDDiZdxL5_EzQt69cGZ4mxqa3nUhIjRl7aL3mBUkv3DVmBPXDbQZd4lhFAR3wJCofoILLqsRjmQMufpP8FHcc7a5v3bEg-9arsNm7P_BJp2A_VRJx8jPlh_aFUI7ei0E50wB8UC6HwtpEo1rHuOoVKrnSMuurjIUdQ9DpAY',
    points: 4,
    exactScores: 0,
    correctOutcomes: 4,
    winRate: '69%',
  },
  {
    rank: 4,
    name: 'Tournament Pro (You)',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCt57pSMGRNJ5vMGbhILCoX4e9b_Sfq21smn3PZfBACn-HnfLbVhlaLRc5Y6rP0rxW5jerf3YtnNumdC7IRCkqJYrxB10SYuIS3RAnArNEIQj4gt1CfIns3_DxDWqrdGdJLAqMsm9Gu-NMBNA0k29tsSkHENkIUeTEH2v_nViPiEVyCuCQC22FsgNFZTwzoH3SuoARoQVsU-NeaCghYmgjk6YFjuJLJNLXiAovBXkSba5j7UoT7Ssd87qmaGmql6hEPK1lJkKxHZes',
    points: 3,
    exactScores: 1,
    correctOutcomes: 0,
    winRate: '50%',
    isUser: true,
  },
];

export const COUNTRIES = [
  { name: 'USA', code: 'USA', flag: 'https://flagcdn.com/w160/us.png' },
  { name: 'Mexico', code: 'MEX', flag: 'https://flagcdn.com/w160/mx.png' },
  { name: 'Canada', code: 'CAN', flag: 'https://flagcdn.com/w160/ca.png' },
  { name: 'Argentina', code: 'ARG', flag: 'https://flagcdn.com/w160/ar.png' },
  { name: 'France', code: 'FRA', flag: 'https://flagcdn.com/w160/fr.png' },
  { name: 'Germany', code: 'GER', flag: 'https://flagcdn.com/w160/de.png' },
  { name: 'Spain', code: 'ESP', flag: 'https://flagcdn.com/w160/es.png' },
  { name: 'England', code: 'ENG', flag: 'https://flagcdn.com/w160/gb-eng.png' },
  { name: 'Portugal', code: 'POR', flag: 'https://flagcdn.com/w160/pt.png' },
  { name: 'Brazil', code: 'BRA', flag: 'https://flagcdn.com/w160/br.png' },
  { name: 'Morocco', code: 'MAR', flag: 'https://flagcdn.com/w160/ma.png' },
  { name: 'Croatia', code: 'CRO', flag: 'https://flagcdn.com/w160/hr.png' },
  { name: 'Netherlands', code: 'NED', flag: 'https://flagcdn.com/w160/nl.png' },
  { name: 'Japan', code: 'JPN', flag: 'https://flagcdn.com/w160/jp.png' },
  { name: 'Korea Republic', code: 'KOR', flag: 'https://flagcdn.com/w160/kr.png' },
  { name: 'Ecuador', code: 'ECU', flag: 'https://flagcdn.com/w160/ec.png' },
];

export const PLAYERS = [
  'Lionel Messi (Argentina)',
  'Kylian Mbappé (France)',
  'Vinícius Júnior (Brazil)',
  'Jude Bellingham (England)',
  'Harry Kane (England)',
  'Lamine Yamal (Spain)',
  'Jamal Musiala (Germany)',
  'Christian Pulisic (USA)',
  'Erling Haaland (Norway)',
  'Cristiano Ronaldo (Portugal)',
  'Bruno Fernandes (Portugal)',
  'Memphis Depay (Netherlands)',
  'Bukayo Saka (England)',
  'Jonathan David (Canada)',
];
